import child from "node:child_process";
import fs from "node:fs/promises";
import path from "node:path";
import {} from "node:zlib";

const filesDir = "files/";
const filesPath = path.resolve(filesDir);
const knownFilesPath = path.resolve("src/knownFiles.ts");

const ents = await fs.readdir(filesPath, { withFileTypes: true });

const fileList = [];

for (const ent of ents) {
  if (!ent.isFile()) continue;
  fileList.push(ent.name);
}

const knownSrc = `\
// This file is generated by scripts/known.mjs
export const knownFiles = ${JSON.stringify(fileList, null, 2)};
`;

await fs.writeFile(knownFilesPath, knownSrc);
