// This file is generated by scripts/known.mjs
export const knownFiles = [
  "381.usdz",
  "381.yjsxg53qh1l.usdz",
  "DartmoorTOP.usdz",
  "DartmoorTOP_a.13gwqpz1xq8.usdz",
  "apple_vision_pro_ios16.usdz",
  "apple_vision_pro_ios16_a.6by9ktfnghw.usdz"
];
