// This file is generated by scripts/known.mjs
export const knownFiles = [
  "381.q2v6iq3uc3o.usdz",
  "381.usdz",
  "DartmoorTOP.usdz",
  "DartmoorTOP_a.mv1csk0g7w.usdz",
  "apple_vision_pro_ios16.usdz",
  "apple_vision_pro_ios16_a.b2fqvgluli.usdz"
];
